### ISSUE TITLE
Speichern von Änderungen nicht möglich

### ISSUE THREAD

**Issue by xanadiu** [MadMax2506/RubyOnRails-Webapp_Versandhandel#6]
Wenn ich einen Artikel bearbeiten und die Änderungen speichern möchte, erhalte ich einen `Routing Error: No route matches [PATCH] "/1/articles/1"`.

Da du das gleiche Formular wie beim Erstellen eines Artikels nutzt, wo das Speichern (bzw. Erstellen) klappt, denke ich, dass für die Bearbeitung das falsche Formularziel übergeben wird. Das betrifft möglicherweise auch andere Models.

**Comment by MadMax2506** [comment]
Das betrifft alle Änderungen
